void laplasKernel( int sizeDiag,
                int sizeFace,
                double *vcs, 
                double *tot,
                double *delta,
                double *gamma,
                int *upperAddr,
                int *lowerAddr,
                int *patchCounter,
                int *pC_Array,
                double *pDiag,
                double *pSource,
                int maxPatches,
                int numberOfPatches,
                double rDelgaG,
                double *h_diag,
                double *h_source,
                double *h_upper,
                double *h_lower
                );